spring.application.name=delivery_app_aopr
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d70d9s7kijhs73darqtg-a.oregon-postgres.render.com:5432/delivery_app_aopr}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:delivery_app_aopr_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0OsLvmfdhhAhdqiJ5jkGbLIfqjT5ZyRl}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
