spring.application.name=delivery_app_aopr
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_app
spring.datasource.username=thzc7
spring.datasource.password=thzc7manda



spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
